"""add codigos verificacion

Revision ID: d2b4ba20f8f8
Revises: 3439cbbd54de
Create Date: 2026-06-06 18:57:24.176225
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd2b4ba20f8f8'
down_revision: Union[str, None] = '3439cbbd54de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codigosVerificacion',
    sa.Column('identificador', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('creadoEn', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiraEn', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['persona'], ['personas.identificador'], ),
    sa.PrimaryKeyConstraint('identificador')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codigosVerificacion')
    # ### end Alembic commands ###
